// Mocks generated by Mockito 5.2.0 from annotations
// in variacao_ativo/test/src/data/data_source/ativo_datasource_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:variacao_ativo/src/data/data_source/ativo_datasource.dart'
    as _i4;
import 'package:variacao_ativo/src/domain/entitie/ativo_entity.dart' as _i2;
import 'package:variacao_ativo/src/domain/entitie/http_response.dart' as _i3;
import 'package:variacao_ativo/src/domain/service/http_service.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeAtivoEntity_0 extends _i1.Fake implements _i2.AtivoEntity {}

class _FakeHttpResponse_1 extends _i1.Fake implements _i3.HttpResponse {}

/// A class which mocks [AtivoDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAtivoDataSource extends _i1.Mock implements _i4.AtivoDataSource {
  MockAtivoDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.AtivoEntity> getVariacaoAtivo() =>
      (super.noSuchMethod(Invocation.method(#getVariacaoAtivo, []),
              returnValue: Future<_i2.AtivoEntity>.value(_FakeAtivoEntity_0()))
          as _i5.Future<_i2.AtivoEntity>);
}

/// A class which mocks [HttpService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpService extends _i1.Mock implements _i6.HttpService {
  MockHttpService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.HttpResponse> get(String? url) => (super.noSuchMethod(
          Invocation.method(#get, [url]),
          returnValue: Future<_i3.HttpResponse>.value(_FakeHttpResponse_1()))
      as _i5.Future<_i3.HttpResponse>);
}
